# Generated by Django 5.1.4 on 2024-12-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название зала')),
                ('seats', models.IntegerField(verbose_name='Количество мест')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('available_equipment', models.CharField(max_length=100, verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'фильм',
                'verbose_name_plural': 'фильмы',
            },
        ),
    ]
