# Generated by Django 5.1.4 on 2024-12-30 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={'verbose_name': 'зал', 'verbose_name_plural': 'залы'},
        ),
    ]
