# Generated by Django 5.1.4 on 2024-12-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_alter_hall_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
