# Generated by Django 5.1.4 on 2024-12-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hall', '0004_alter_hall_id'),
        ('movie', '0002_auto_20241230_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=50, verbose_name='Время начала')),
                ('end_time', models.CharField(max_length=50, verbose_name='Время окончания ')),
                ('available_seats', models.IntegerField(verbose_name='Доступные места')),
                ('hall', models.ManyToManyField(related_name='Зал', to='hall.hall')),
                ('movie', models.ManyToManyField(related_name='Фильм', to='movie.movie')),
            ],
        ),
    ]
