# Generated by Django 5.1.4 on 2025-01-14 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0004_alter_hall_id'),
        ('movie', '0002_auto_20241230_1330'),
        ('period', '0002_sessions_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='hall',
        ),
        migrations.AlterField(
            model_name='sessions',
            name='movie',
            field=models.ManyToManyField(to='movie.movie', verbose_name='Фильм'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='hall',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='hall.hall', verbose_name='Зал'),
            preserve_default=False,
        ),
    ]
