# Generated by Django 5.1.4 on 2025-01-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wallet',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
