# Generated by Django 5.1.4 on 2025-01-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_customuser_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='wallet',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
