# Generated by Django 5.1.4 on 2025-01-14 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('period', '0002_sessions_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_place', models.IntegerField(verbose_name='Количество мест')),
                ('payment_type', models.CharField(choices=[('Наличными', 'Наличными'), ('Карта', 'Карта')], verbose_name='Тип оплаты')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period', to='period.sessions', verbose_name='Период')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирования',
                'verbose_name_plural': 'Бронирование',
            },
        ),
    ]
