# Generated by Django 5.1.4 on 2025-01-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bonus',
            field=models.CharField(blank=True, null=True, verbose_name='Твои бонусы'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.IntegerField(blank=True, default='sdf', null=True, verbose_name='Цена билета'),
        ),
    ]
