# Generated by Django 5.1.4 on 2025-01-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_bonus_alter_booking_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bonus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Твои бонусы'),
        ),
    ]
