# Generated by Django 5.1.4 on 2024-12-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('duration_minutes', models.IntegerField(max_length=100, verbose_name='Продолжительность')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='Рейтинг')),
                ('poster_url', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Постер')),
                ('genre', models.ManyToManyField(related_name='Жанр', to='movie.genre')),
            ],
            options={
                'verbose_name': 'фильм',
                'verbose_name_plural': 'фильмы',
            },
        ),
    ]
