# Generated by Django 5.1.4 on 2024-12-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
    ]
