# Generated by Django 5.1.4 on 2024-12-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration_minutes',
            field=models.IntegerField(verbose_name='Продолжительность'),
        ),
    ]
